<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_").Replace("Module",""))</RootNamespace>
    <BaseOutputPath>..\bin</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ElShrine.VisualTool\ElShrine.VisualTool.csproj" />
  </ItemGroup>

</Project>
