<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>ElShrine</RootNamespace>
    <BaseOutputPath>..\bin</BaseOutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ElShrineLib.Wpf.Generators.Attributes" Version="1.0.0" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

    <ItemGroup>
		<AssemblyAttribute Include="System.Windows.ThemeInfoAttribute">
			<_Parameter1>System.Windows.ResourceDictionaryLocation.None</_Parameter1>
			<_Parameter1_IsLiteral>true</_Parameter1_IsLiteral>

			<_Parameter2>System.Windows.ResourceDictionaryLocation.SourceAssembly</_Parameter2>
			<_Parameter2_IsLiteral>true</_Parameter2_IsLiteral>
		</AssemblyAttribute>
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ElShrineLib.Graphics\ElShrineLib.Graphics.csproj" />
  </ItemGroup>
	
  <ItemGroup>
	  <Analyzer Include="..\ElShrine.Wpf.Generators\bin\Release\netstandard2.0\ElShrineLib.Wpf.Generators.dll" />
  </ItemGroup>
	
  <ItemGroup>
    <Folder Include="Themes\" />
  </ItemGroup>

</Project>
