<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>ElShrine</RootNamespace>
    <BaseOutputPath></BaseOutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<LangVersion>preview</LangVersion>
	<PackageOutputPath>..\bin\Packages</PackageOutputPath>
	  <DebugType>embedded</DebugType>
	  
	  <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
  </PropertyGroup>

    <ItemGroup>
		<AssemblyAttribute Include="System.Windows.ThemeInfoAttribute">
			<_Parameter1>System.Windows.ResourceDictionaryLocation.None</_Parameter1>
			<_Parameter1_IsLiteral>true</_Parameter1_IsLiteral>

			<_Parameter2>System.Windows.ResourceDictionaryLocation.SourceAssembly</_Parameter2>
			<_Parameter2_IsLiteral>true</_Parameter2_IsLiteral>
		</AssemblyAttribute>
	</ItemGroup>
	
  
	
  <ItemGroup>
    <Folder Include="Themes\" />
  </ItemGroup>
	
  
	
  <ItemGroup>
    <PackageReference Include="ElShrineLib.Wpf.Generators" Version="1.0.0" />
  </ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\ElShrineLib.Graphics\ElShrineLib.Graphics.csproj" />
  </ItemGroup>

</Project>
