<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>$(MSBuildProjectName)</RootNamespace>
    <BaseOutputPath>..\bin</BaseOutputPath>
    <AssemblyName>$(MSBuildProjectName)</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ElShrineLib.Wpf\ElShrineLib.Wpf.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ElShrineLib.Wpf.Generators.Attributes">
      <HintPath>..\ElShrine.Wpf.Generators\bin\Release\netstandard2.0\ElShrineLib.Wpf.Generators.Attributes.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
