<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	  <RunPostBuildEvent>Always</RunPostBuildEvent>
	  <TargetFramework>net8.0-windows</TargetFramework>
	  <RootNamespace>ElShrine</RootNamespace>
	  <BaseOutputPath></BaseOutputPath>
	  <LangVersion>preview</LangVersion>
	  <OutputType>Exe</OutputType>
	  <PackageOutputPath>..\bin\Packages</PackageOutputPath>
	  <DebugType>embedded</DebugType>

	  <EmbedAllSources>true</EmbedAllSources>

	  <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>

	  <StartupObject>ElShrine.Debug.DebugConsoleProgram</StartupObject>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'" />
  <ItemGroup>
    <Folder Include="Async\" />
  </ItemGroup>

</Project>
