<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	  <RunPostBuildEvent>Always</RunPostBuildEvent>
	  <TargetFramework>net8.0-windows</TargetFramework>
	  <RootNamespace>ElShrine</RootNamespace>
	  <BaseOutputPath>..\bin</BaseOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'" />

</Project>
